name: Markdown Checks

on:
  pull_request:
    branches:
      - main

jobs:
  markdown-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Markdown
        uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"

      - name: Spell check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.md"
